baseURL = "https://retrolog.io/"
languageCode = "en-gb"
title = "Retrolog.io"

theme = "papaya"

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/blog/:title/"

# The value of pre is the icon name in https://feathericons.com/
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
  description = "Read about management and leadership in software engineering. Learn from the past and move forward!"
  dateFormat = "Jan 2, 2006"
  authorName = "Pedro Lopez"
  privacyPolicyUrl = "/pages/privacy-policy"
  #googleAdSense = "ca-pub-9945087415580189"
  googleAnalytics = "UA-156682837-1"
  amazonAffiliates = true
  amazonAffiliatesSearchKey = "pragmatic programmer"
  amazonAffiliatesTrackingId = "retrolog-21"
  amazonAffiliatesButtonUrl = "https://www.amazon.co.uk/gp/search?ie=UTF8&tag=retrolog-21&linkCode=ur2&linkId=29bcc9e275d4c219971ab43b8f4ca0b3&camp=1634&creative=6738&index=books&keywords=pragmatic programmer"
  amazonAffiliatesWidgetUrl = "//z-eu.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&Operation=GetScript&ID=OneJS&WS=1&Marketplace=GB"
  amazonAffiliatesRecommendationUrl = [
    { link = "https://www.amazon.co.uk/gp/product/1480247871/ref=as_li_tl?ie=UTF8&camp=1634&creative=6738&creativeASIN=1480247871&linkCode=as2&tag=retrolog-21&linkId=c1d15c35a66115364b11a6626de1bdfe", image = "//ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=GB&ASIN=1480247871&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=retrolog-21", pixel = "//ir-uk.amazon-adsystem.com/e/ir?t=retrolog-21&l=am2&o=2&a=1480247871" },
    { link = "https://www.amazon.co.uk/gp/product/1680502395/ref=as_li_tl?ie=UTF8&camp=1634&creative=6738&creativeASIN=1680502395&linkCode=as2&tag=retrolog-21&linkId=0ab725f3fb06b73059b33285abdd02e5", image = "//ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=GB&ASIN=1680502395&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=retrolog-21", pixel = "//ir-uk.amazon-adsystem.com/e/ir?t=retrolog-21&l=am2&o=2&a=1680502395" },
    { link = "https://www.amazon.co.uk/gp/product/B00O92Q6D0/ref=as_li_tl?ie=UTF8&camp=1634&creative=6738&creativeASIN=B00O92Q6D0&linkCode=as2&tag=retrolog-21&linkId=758e4dd5a36e75d4aa9207a8a671aad3", image = "//ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=GB&ASIN=B00O92Q6D0&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=retrolog-21", pixel = "//ir-uk.amazon-adsystem.com/e/ir?t=retrolog-21&l=am2&o=2&a=B00O92Q6D0" },
    { link = "https://www.amazon.co.uk/gp/product/1422188612/ref=as_li_tl?ie=UTF8&camp=1634&creative=6738&creativeASIN=1422188612&linkCode=as2&tag=retrolog-21&linkId=79701fa4159df0dfd4540a8d3a92ce11", image = "//ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=GB&ASIN=1422188612&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=retrolog-21", pixel = "//ir-uk.amazon-adsystem.com/e/ir?t=retrolog-21&l=am2&o=2&a=1422188612" },
    { link = "https://www.amazon.co.uk/gp/product/1544972687/ref=as_li_tl?ie=UTF8&camp=1634&creative=6738&creativeASIN=1544972687&linkCode=as2&tag=retrolog-21&linkId=3cc718de15b5718a213261a8c019936d", image = "//ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=GB&ASIN=1544972687&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=retrolog-21", pixel = "//ir-uk.amazon-adsystem.com/e/ir?t=retrolog-21&l=am2&o=2&a=1544972687" },
    { link = "https://www.amazon.co.uk/gp/product/0321125215/ref=as_li_tl?ie=UTF8&camp=1634&creative=6738&creativeASIN=0321125215&linkCode=as2&tag=retrolog-21&linkId=9b96f729fc0dc6e0f66cb9ad71d5b02b", image = "//ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=GB&ASIN=0321125215&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=retrolog-21", pixel = "//ir-uk.amazon-adsystem.com/e/ir?t=retrolog-21&l=am2&o=2&a=0321125215" },
    { link = "https://www.amazon.co.uk/gp/product/149195177X/ref=as_li_tl?ie=UTF8&camp=1634&creative=6738&creativeASIN=149195177X&linkCode=as2&tag=retrolog-21&linkId=33ae29c3f844186f20137937f4249835", image = "//ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=GB&ASIN=149195177X&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=retrolog-21", pixel = "//ir-uk.amazon-adsystem.com/e/ir?t=retrolog-21&l=am2&o=2&a=149195177X" },
  ]

[social]
  twitter = "Retrologio"

[deployment]
  [[deployment.targets]]
  name = "s3"
  URL = "s3://retrolog.io?region=eu-west-2"

[markup]
  [markup.highlight]
    style = "friendly"
    tabWidth = 2