baseURL = "https://plopcas.github.io/retrolog/"
languageCode = "en-gb"
title = "Retrolog.io"

theme = "papaya"
canonifyURLs = true

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/blog/:title/"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
  description = "Read about management and leadership in software engineering. Learn from the past and move forward!"
  dateFormat = "Jan 2, 2006"
  authorName = "Pedro Lopez"
  privacyPolicyUrl = "/pages/privacy-policy"

[markup]
  [markup.highlight]
    style = "friendly"
    tabWidth = 2
