baseURL = "https://retrolog.io/"
languageCode = "en-gb"
title = "Retrolog.io"

theme = "papaya"

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/blog/:title/"

# The value of pre is the icon name in https://feathericons.com/
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
  description = "Read about management and leadership in software engineering. Learn from the past and move forward!"
  dateFormat = "Jan 2, 2006"
  authorName = "Pedro Lopez"
  privacyPolicyUrl = "/pages/privacy-policy"
  googleAnalytics = "UA-156682837-1"
  monetization = "$ilp.uphold.com/hkmXm3ghEK3R"

[social]
  twitter = "Retrologio"

[deployment]
  [[deployment.targets]]
  name = "s3"
  URL = "s3://retrolog.io?region=eu-west-2"

[markup]
  [markup.highlight]
    style = "friendly"
    tabWidth = 2